//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Watch_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Product
    {
        public int Customer_ID { get; set; }
        public int Product_ID { get; set; }
        public string CusPro_Name { get; set; }
        public Nullable<decimal> CusPro_Price { get; set; }
        public string CusPro_Image { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
