//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Watch_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public int Discount_ID { get; set; }
        public string Discount_Name { get; set; }
        public Nullable<decimal> Discount_Price { get; set; }
        public Nullable<int> Discount_Quantity { get; set; }
        public Nullable<System.DateTime> Expiration_Date { get; set; }
    }
}
