//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Watch_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Import
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Import()
        {
            this.Import_Details = new HashSet<Import_Details>();
        }
    
        public int Import_ID { get; set; }
        public string Importer { get; set; }
        public Nullable<System.DateTime> Import_Date { get; set; }
        public Nullable<decimal> Import_Total { get; set; }
        public string Import_Note { get; set; }
        public Nullable<int> Provider_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Import_Details> Import_Details { get; set; }
        public virtual Providerr Providerr { get; set; }
    }
}
