//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Watch_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderID_STT { get; set; }
        public int Order_ID { get; set; }
        public int Product_ID { get; set; }
        public string Product_Name { get; set; }
        public Nullable<int> Product_Quantity { get; set; }
        public Nullable<decimal> Into_Money { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Order Order { get; set; }
    }
}
